name: doctorapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  keyboard_visibility: ^0.5.2
  flutter:
    sdk: flutter
  typicons_flutter: ^0.3.1
  emoji_picker: ^0.1.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  file_picker: ^1.13.2
  chips_choice: ^1.2.0
  camera:
  path_provider:
  image_picker: ^0.6.7+4
  path:
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  agora_rtc_engine: 1.0.5
  stream_chat_flutter: ^0.2.1
  permission_handler: ^3.0.0
  fluttertoast: ^7.0.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/man_pic.jpg
    - images/consult.jpeg
    - images/dr.jpeg


  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Regular.ttf
        - asset: fonts/Oxygen-Bold.ttf
          weight: 700